[package]
name = "posh-tabcomplete"
version = "0.2.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Blazing fast tab completion for powershell."
repository = "https://github.com/domsleee/posh-tabcomplete"
readme = "README.md"

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
itertools = "0.12"
log = "0.4.21"
nu-cli = "0.91.0"
nu-command = "0.91.0"
nu-cmd-lang = "0.91.0"
nu-engine = "0.91.0"
nu-parser = "0.91.0"
nu-protocol = "0.91.0"
reedline = "0.30.0"
regex = "1.10.3"
env_logger = "0.11.3"

[dev-dependencies]
diff = "0.1"
tempfile = "3.10"
filetime = "0.2.23"
rstest = "0.18.2"
rstest_reuse = "0.6.0"
speculoos = "0.11.0"

[[bin]]
name = "posh-tabcomplete"
path = "src/main.rs"

[profile.release]
lto = true
strip = true
opt-level = "z"
codegen-units = 1
panic = "abort"
