[package]
name = "posh-tabcomplete"
version = "0.1.6"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Blazing fast tab completion for powershell."
repository = "https://github.com/domsleee/posh-tabcomplete"
readme = "README.md"

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
itertools = "0.11"
log = "0.4.17"
nu-cli = "0.87.0"
nu-command = "0.87.0"
nu-cmd-lang = "0.87.0"
nu-parser = "0.87.0"
nu-protocol = "0.87.0"
reedline = "0.26.0"
nu-engine = "0.87.0"
regex = "1.7.1"
env_logger = "0.10.0"

[dev-dependencies]
diff = "0.1"
tempfile = "3.3"
filetime = "0.2"
rstest = "0.17.0"
rstest_reuse = "0.5.0"
speculoos = "0.11.0"

[[bin]]
name = "posh-tabcomplete"
path = "src/main.rs"

[profile.release]
lto = true
strip = true
opt-level = "z"
codegen-units = 1
