[package]
name = "posh-tabcomplete"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Blazing fast tab completion for powershell."
repository = "https://github.com/domsleee/posh-tabcomplete"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/{ version }/{ name }-{ version }-{ target }.{ archive-format }"
pkg-fmt = "tgz"

[package.metadata.binstall.overrides.x86_64-pc-windows-msvc]
pkg-fmt = "zip"

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
itertools = "0.10.5"
log = "0.4.17"
nu-cli = "0.76.0"
nu-command = "0.76.0"
nu-parser = "0.76.0"
nu-protocol = "0.76.0"
reedline = "0.16.0"
nu-engine = "0.76.0"
regex = "1.7.1"

[dev-dependencies]
diff = "0.1"
tempfile = "3.3"
filetime = "0.2"
test-case = "2.2"
assertor = "0.0.1"
rstest = "0.16.0"
rstest_reuse = "0.5.0"

[[bin]]
name = "tabcomplete"
path = "src/main.rs"
